name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, ready_for_review]

# cancel running actions for current PR if new commits were pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  depandabot-modify-changelog:
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - run: |
          insertText="### dependabot: \\\#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}"

          # check if file doesn't contain the text already
          if ! grep -q "$insertText" CHANGELOG.md; then
            echo "Changelog entry not found, adding it"
            sed -i "/## \[Unreleased\]/a \
            $insertText" CHANGELOG.md
          else
            echo "Changelog entry already exists, skipping"
            exit 0
          fi

      - name: initialize mandatory git config
        run: |
          git config user.name "GitHub Changelog Bot"
          git config user.email changelog-bot@neolution.ch

      - run: npx prettier --write CHANGELOG.md

      - name: commit and push
        run: |
          git add CHANGELOG.md
          git commit -m "Add changelog entry for ${{ github.event.pull_request.title }}"
          git push

  check-changelog:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Check if changelog was touched
        run: |
          changelogFound=$(echo ${{ steps.changed-files.outputs.all_changed_files }} | grep -ow "CHANGELOG.md" | wc -w)
          if [ $changelogFound -eq 0 ]; then
            echo '### :boom: Please update the changelog accordingly (https://keepachangelog.com)' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

  ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        react-version: [^18.2.0, ^19.0.0]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn --frozen-lockfile
      - run: yarn add react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} --dev --verbose
      - run: yarn lint
      - run: yarn build
      - run: yarn prettier-check

      # Run cypress tests
      - run: yarn add next@^12.0.0
        working-directory: ./cypress
        if: ${{ matrix.react-version == '^16.0.0' || matrix.react-version == '^17.0.0' }}
      - run: yarn add cypress@^13.0.0 --dev
        working-directory: ./cypress
        if: ${{ matrix.react-version == '^16.0.0' || matrix.react-version == '^17.0.0' }}
      - run: yarn --frozen-lockfile
        working-directory: ./cypress
      # - run: yarn lint
      #   working-directory: ./cypress
      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          exclude: "node_modules|dist|.git|.husky"
          path: .
          depth: 4
      - run: yarn cypress run --component
        working-directory: ./cypress

      # Upload screenshots/videos
      - name: Upload snapshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-snapshots-${{ matrix.node-version }}
          path: |
            ./cypress/cypress/screenshots
            ./cypress/cypress/videos
