name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, ready_for_review]

# cancel running actions for current PR if new commits were pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: yarn prettier-check

      # Run cypress tests
      - run: yarn
        working-directory: ./cypress
      # - run: yarn lint
      #   working-directory: ./cypress
      - run: yarn cypress run --component
        working-directory: ./cypress
