name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, ready_for_review]

# cancel running actions for current PR if new commits were pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changelog:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Check if changelog was touched
        run: |
          changelogFound=$(echo ${{ steps.changed-files.outputs.all_changed_files }} | grep -ow "CHANGELOG.md" | wc -w)
          if [ $changelogFound -eq 0 ]; then
            echo '### :boom: Please update the changelog accordingly (https://keepachangelog.com)' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

  ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn prettier-check

      # Run cypress tests
      - run: yarn --frozen-lockfile
        working-directory: ./cypress
      # - run: yarn lint
      #   working-directory: ./cypress
      - run: yarn cypress run --component
        working-directory: ./cypress
